# Generated by Django 5.1.4 on 2024-12-09 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('region', models.CharField(max_length=100, verbose_name='Region')),
                ('consumption', models.DecimalField(decimal_places=2, help_text='Utilisez une virgule comme séparateur décimal (ex: 42,5)', max_digits=10, verbose_name='Consumption (TWh)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Energy Data',
                'verbose_name_plural': 'Energy Data',
                'ordering': ['-date', 'region'],
                'indexes': [models.Index(fields=['date', 'region'], name='analytics_e_date_adccc4_idx'), models.Index(fields=['region'], name='analytics_e_region_a79500_idx')],
            },
        ),
    ]
